FROM  node:alpine

COPY . .

RUN npm install

EXPOSE 8000

CMD [ "npm", "start" ]

#$docker image build -t muchirajunior/todo-express .
#$docker run -it muchirajunior/todo-express

#$docker commit container  muchirajunior/todo-express:1